application: omssssampleapp
version: 1
runtime: python
api_version: 1

handlers:
- url: /_ah/login_required
  script: openid_login.py

- url: /(.*\.(xml))
  static_files: static/\1
  upload: static/(.*\.(xml))

- url: /event
  script: main.py

- url: /
  script: main.py

- url: /main
  script: main.py
  login: required
